### ISSUE TITLE
Change maintainer of project Stalmarck

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#104]
**Project name and URL:** https://github.com/coq-community/stalmarck

**Current maintainer:** @herbelin 

**Status:** maintained

**New maintainer:** looking for a volunteer

@herbelin is currently maintaining this project (and also [qarith-stern-brocot](https://github.com/coq-community/qarith-stern-brocot) and [bertrand](https://github.com/coq-community/bertrand)), but because he's also the one taking care of all the remaining coq-contribs, he'd gladly accept if someone else wanted to take over this package (or one of the other two I suppose). Cf. https://github.com/coq-community/stalmarck/pull/12#issuecomment-636029984.

**Comment by palmskog** [comment]
I have used Stalmarck for proof engineering research in the past, and it's currently part of our benchmark suite for the [mCoq](https://github.com/EngineeringSoftware/mcoq) tool. Stalmarck would likely benefit a lot from more build automation, in particular using Dune instead of coq_makefile. I believe issues like coq-community/stalmarck#8 are crucial to address.

Hence, I'd like to volunteer to maintain Stalmarck, but under the assumption that it would be welcome to join Coq's CI (mostly since I don't have the cycles to follow the changes to Coq's plugin API).

**Comment by Zimmi48** [comment]
>it would be welcome to join Coq's CI

That's a correct assumption to make: by Coq's own ML API policy, any plugin is welcome to join Coq's CI.

**Comment by palmskog** [comment]
>  any plugin is welcome to join Coq's CI

I believe one has to demonstrate that it builds at least once with Coq `master` though, right? This is currently hard to tell if it does.

**Comment by palmskog** [comment]
OK, how about the following: I'll take over as maintainer when the CI on Stalmarck's `master` branch passes. Then I'll just submit it to Coq's CI and take things from there.

Is this fine by you, @herbelin?

**Comment by Zimmi48** [comment]
> I believe one has to demonstrate that it builds at least once with Coq `master` though, right?

That's correct. CI will check this upon inclusion.

>This is currently hard to tell if it does.

It likely doesn't (according to its CI).

**Comment by herbelin** [comment]
> It likely doesn't (according to its CI).

It should work now.

> Is this fine by you, @herbelin?

Yes, it is. Thanks for your involvement.

**Comment by Zimmi48** [comment]
We are now at the state where @palmskog said he could take over.

**Comment by palmskog** [comment]
Maintainer change is official now as per coq-community/stalmarck#13 - so I'm closing this.

Something to think about: maybe we want to keep explicit maintainership history of projects somewhere, e.g., maintainers in `meta.yml` have a flag like `current`.
