### ISSUE TITLE
Proposal to move project coq-dpdgraph to coq-community

### ISSUE THREAD

**Issue by ybertot** [coq-community/manifesto#131]
**Project name:** coq-dpdgraph

**Initial author(s):** Anne Pacalet (@Karmaki), Yves Bertot, Olivier Pons

**Current URL:** https://github.com/karmaki/coq-dpdgraph

**Kind:** OCaml plugin

**License:** GNU LGPL 2.1

**Description:** an Ocaml plugin to traverse the dependency graph between defined functions, types, and theorems in the Coq memory.

**Status:**   It is maintained, part of Coq-CI, with a new version produced for each release of Coq, thanks to the kind help of the main Coq developers.

**New maintainer:** Yves Bertot, will be happy to onboard any other volunteer.

**Comment by palmskog** [comment]
Once the transfer is done, I will help set up the usual metadata file (`meta.yml`) and basic CI configuration.

**Comment by Karmaki** [comment]
@ybertot: do you want me to push the current version to a new https://github.com/coq-community/coq-dpdgraph repository, or have you planned to do it yourself? (since you said you started preparing a new version, you may have local modifications?)

**Comment by palmskog** [comment]
@Karmaki if you use GitHub's repository transfer feature ("Settings", then "Danger Zone"), the old repository URL will still work in the new location in the `coq-community` organization due to URL forwarding. So Yves will not have any trouble pushing new outstanding changes either before or after the transfer.

Note that we don't recommend creating any completely *new* repository (in lieu of transfer), since then all outstanding links will still go to the "old" repo.

**Comment by Karmaki** [comment]
Oh I see. I did not know this "transfer feature". I just did it then.

**Comment by palmskog** [comment]
Given that repository has been successfully moved, I think we can close this issue and continue the discussion as issues in the coq-dpdgraph repo.

**Comment by Zimmi48** [comment]
@ybertot commented in the platform discussion:

>I will be happy to commit to maintaining this package. Still, I would like this to be handed over to other volunteers, as soon as possible.

Should we reopen an issue to advertise that this project is looking for new maintainers?
