### ISSUE TITLE
Volunteer co-maintainer needed for Docker-Coq

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#144]
The Coq Team and Coq-community are looking for a volunteer co-maintainer of the [Docker-Coq](https://github.com/coq-community/docker-coq) project, which provides [Docker container](https://www.docker.com/resources/what-container/) images of many versions of Coq as a service to Coq users.

Docker-Coq is an open source project on GitHub under the BSD-3-Clause license. It maintains definitions of a set of Docker images that provide a basic Coq environment for continuous integration and local use. Thanks to the [docker-keeper](https://gitlab.com/erikmd/docker-keeper) software, images built from Docker-Coq definitions are continuously deployed to the [public Docker registry](https://hub.docker.com/r/coqorg/coq), where users can pull them without worry of rate limitations.

Desirable skills:
- Familiarity with container software like Docker
- Familiarity with software continuous integration and build automation, in particular on GitHub and/or GitLab
- Basic shell scripting
- Basic Python programming

Maintainer core tasks:
- Create and deploy new Coq Docker definitions to the Docker registry after Coq (pre-)releases.
- Monitor the use of Coq Docker images for continuous integration on GitHub/GitLab and rebuild images when necessary.
- Work with the current Docker-Coq and Docker-Keeper [maintainer](https://github.com/erikmd) to further develop and automate the toolchain.

During their tenure, a maintainer will be considered part of the [Coq Team](https://coq.inria.fr/coq-team.html) and credited for their work in release notes for Coq releases, for example on [Zenodo](https://doi.org/10.5281/zenodo.1003420).

Please respond to this GitHub issue with your motivation, and a short summary of relevant experience, for becoming a Docker-Coq maintainer. The maintainer will be selected from the issue responders by the Coq Team and Coq-community owners.

**Comment by himito** [comment]
Dear @palmskog,

My name is [Jaime ARIAS](https://www.jaime-arias.fr/) and I'm a CNRS research engineer working for the  [LoVe](https://lipn.univ-paris13.fr/love/) (Logique et Vérification) team at the Laboratoire d'Informatique de Paris Nord ([LIPN](https://lipn.univ-paris13.fr/)). Regarding my experience, please check my [CV](https://www.jaime-arias.fr/pdfs/resume.pdf).
Why I'm interested in this project ? Because I believe that software preservation and interoperability are an essential challenge for today's world (I'm a [Software Heritage ambassador](https://www.softwareheritage.org/ambassadors/)), and even more for such an important tool as Coq. So I would be very happy to see that Coq remains a tool that can be used by everyone, without exception.

**Comment by palmskog** [comment]
@himito thank you for volunteering! Software preservation is indeed an important goal of Coq-community and Docker-Coq in particular.

Note that we will keep the issue open for one week from when it was first created. Then, on January 24, 2023, we will close the issue and let you know the decision on the maintainership.

**Comment by Zimmi48** [comment]
Thanks again @himito! On behalf of the Coq team and Coq-community, we appoint you as Docker-Coq co-maintainer. @erikmd will get in touch with you to arrange a first Docker-Coq video meeting. You will also receive an invitation to join Coq-community. Note that this gives you write access to every Coq-community repos (although the main branch is generally protected so that only appointed maintainers can push). We will also give you admin access to the Docker-Coq repo once you have joined the organization.

**Comment by himito** [comment]
Thank you guys, it's an honour to be part of the Coq community.

**Comment by erikmd** [comment]
> We will also give you admin access to the Docker-Coq repo once you have joined the organization.

This is now done.

I think we can close this issue then.

Thank you all 👍
