### ISSUE TITLE
dblib is unmaintained

### ISSUE THREAD

**Issue by KevOrr** [coq-community/manifesto#71]
## Move a project to coq-community ##

**Project name and URL:** [dblib](https://github.com/coq-contribs/dblib)

**Current maintainer:** ?

**Status:** unmaintained

**New maintainer:** I volunteer as tribute

See coq-contribs/dblib#1

**Comment by Zimmi48** [comment]
First, thank you @KevOrr for proposing to maintain this project.

FWIW, some additional info:

**License:** GPL 3.0

**Initial author:** François Pottier (@fpottier)

There also exist https://github.com/fpottier/dblib which appears unmaintained too but is more interesting as a repository because it contains more commit history information, and more recent improvements by @gasche in particular. If @fpottier agrees, I propose we transfer the latter to coq-community and simply mark the coq-contribs one with the new URL, and archive it (like we did for [paco](https://github.com/coq-contribs/paco) and [relation-algebra](https://github.com/coq-contribs/relation-algebra)).

**Comment by fpottier** [comment]
Indeed, I have not maintained dblib, partly by lack of time, partly because I think it is largely superseded by more recent and more ambitious projects like [Autosubst](https://www.ps.uni-saarland.de/autosubst/). If someone is willing to maintain it, that's fine with me. Porting it to recent versions of Coq may require some work, though, as there are some complicated and fragile tactics in there.

**Comment by Zimmi48** [comment]
@KevOrr Can you confirm your interest in maintaining this package after this additional information? If yes, we can proceed with transferring @fpottier's repository.

**Comment by KevOrr** [comment]
Thank you @fpottier for the additional information. I agree it makes more sense to use [fpottier/dblib](https://github.com/fpottier/dblib) and archive [coq-contribs/dblib](https://github.com/coq-contribs/dblib). I am still interested in maintaining.

I'll figure out some time this week to see if anything (and if so, what) from the coq-community history needs to be cherry-picked in. It appears that [fpottier/dblib](https://github.com/fpottier/dblib) has the same issue that coq-contribs/dblib#1 fixes, so I'm just going to close that PR and apply the same fix to the other repo.

**Comment by Zimmi48** [comment]
Good. I've sent an invitation to join coq-community to both @KevOrr and @fpottier.
@fpottier: once you accept the invitation, you should be able to transfer your repository from the repository settings.

**Comment by fpottier** [comment]
What transfer would you like me to do exactly? Transfer fpottier/dblib to coq-community?

**Comment by palmskog** [comment]
> Transfer fpottier/dblib to coq-community [organization]?

Yes, that's the idea.

**Comment by fpottier** [comment]
Done.
