### ISSUE TITLE
A list of Coq resources maintained by community

### ISSUE THREAD

**Issue by anton-trunov** [coq-community/manifesto#73]
## Meta-issue ##

This is based on a recent Gitter discussion with @palmskog.

For instance, there is [awesome-ocaml](https://github.com/ocaml-community/awesome-ocaml) list.

Should we create something like this for Coq projects?

**Comment by palmskog** [comment]
Some observations from my side:
- better to focus on listing code repositories than documentation, books, and papers, which are already listed elsewhere
- code repository listing should be completely manual (e.g., not use GitHub stars) and could possibly even include last known Coq version known to be compatible with the project
- ideally it should be possible to use several criteria to find a project, e.g., domain, libraries used, ...

**Comment by palmskog** [comment]
Thanks to the work of Maxime, we now have machine-readable listings of Coq OPAM archive projects: https://coq.inria.fr/opam/coq-packages.json

However, many useful projects do not have releases, and have no packages in the OPAM archive.

For reference, the following automatically generated lists of Coq GitHub projects already exist:
https://github.com/xgrommx/coq-ecosystem
https://github.com/uhub/awesome-coq

**Comment by Zimmi48** [comment]
https://github.com/xgrommx/coq-ecosystem does not seem to me to bring anything better than https://github.com/topics/coq. [BTW, there is a related issue: coq/coq#10507.]

As for https://github.com/uhub/awesome-coq, it looks manually curated to me, even if the categorization should be improved and more data should be added (for instance, I noticed at least one unmaintained repo in there).
Since an awesome-coq list already exists, it seems to me that it would make more sense to transfer it to coq-community like what ocaml-community did rather than to start a new competitor. BTW, the [awesome list movement](https://github.com/sindresorhus/awesome) is very strong (100,000 stars for the meta-repo) and it makes a lot of sense to free-ride on this.
The awesome-coq list is not yet in the meta awesome repo, but it is already in the [awesome-software-quality repo](https://github.com/ligurio/awesome-software-quality).

cc @uhub

**Comment by palmskog** [comment]
We decided to start a new awesome-coq list in the end: https://github.com/coq-community/awesome-coq

**Comment by ccding** [comment]
I am the owner of https://github.com/uhub/awesome-coq (@uhub is an organization account)

Sorry I was traveling recently and didn't have time to read GitHub messages. Please let me know if you need any help.

**Comment by anton-trunov** [comment]
Hi @ccding,

 Your contributions are very welcome! Feel free to fire up a PR or post an issue.

**Comment by anton-trunov** [comment]
Looks like this issue can be closed and any further discussion could be moved to the issues of https://github.com/coq-community/awesome-coq
